# Generated by Django 3.2.7 on 2021-09-13 06:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_alter_bloglistmodel_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloglistmodel',
            name='likes',
            field=models.ManyToManyField(related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
